services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 24feedback
    ports:
      - "5432:5432"
    restart: unless-stopped
    hostname: postgres

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 24feedback
      POSTGRES_HOST: postgres
      PORT: 5000
    restart: unless-stopped